# Generated by Django 5.1.8 on 2025-05-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0010_reservation_room_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="card_holder_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="reservation",
            name="card_last4",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
