# Generated by Django 5.1.8 on 2025-05-09 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotel_app", "0011_reservation_card_holder_name_reservation_card_last4"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="card_holder_name",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="card_last4",
        ),
    ]
